### ISSUE TITLE
Collection TODO list

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.cockroachdb#5]
##### SUMMARY
Collection TODO list

TODO:

- [x] Figure out if something related to Galaxy needs to be done.
- [x] Setup GHA CI unit / sanity testing.
- [x] Setup GHA CI integration after merging this [PR](https://github.com/ansible/ansible/pull/75498).
- [x] Add to Zuul to publish on Galaxy.
- [x] Publish 0.1.0 on Galaxy
- [x] Add CI badges after.
- [x] Reach out to CockroachDB communities.
- [ ] Add more CockroachDB version to CI.
- [x] Codecov
